const fs = require('fs');

const data = JSON.parse(fs.readFileSync('mock-octopus.json', 'utf8'));

let htmlOutput = `<!-- Auto-generated by L.A.R.Z. (Open Design Skill) from Figma: ${data.name} -->\n`;
htmlOutput += `<style>\n  .od-layer { position: absolute; }\n</style>\n\n`;

// Add a container for GSAP animation targeting
htmlOutput += `<div id="lower-third-container">\n`;

data.layers.forEach(layer => {
    let css = `left: ${layer.x}px; top: ${layer.y}px; `;
    
    if (layer.type === 'SHAPE') {
        const bg = `rgba(${layer.style.fill.r}, ${layer.style.fill.g}, ${layer.style.fill.b}, ${layer.style.fill.a})`;
        css += `width: ${layer.width}px; height: ${layer.height}px; background-color: ${bg}; `;
        // Let's add some clip-path for that edgy news look
        css += `clip-path: polygon(0 0, 100% 0, 95% 100%, 0% 100%); `;
        htmlOutput += `  <div class="od-layer lower-third-element" style="${css}"></div>\n`;
    } 
    else if (layer.type === 'TEXT') {
        const col = `rgba(${layer.style.color.r}, ${layer.style.color.g}, ${layer.style.color.b}, ${layer.style.color.a})`;
        css += `color: ${col}; font-family: '${layer.style.fontFamily}'; font-size: ${layer.style.fontSize}px; font-weight: ${layer.style.fontWeight}; `;
        if (layer.style.letterSpacing) css += `letter-spacing: ${layer.style.letterSpacing};`;
        htmlOutput += `  <div class="od-layer lower-third-element" style="${css}">${layer.text}</div>\n`;
    }
});

htmlOutput += `</div>\n\n`;

// Add Hyperframes GSAP Logic
htmlOutput += `<script>
    // L.A.R.Z. injects the signature FFWD animation
    const ltTimeline = gsap.timeline();
    // Set initial state
    gsap.set('.lower-third-element', { x: -800, opacity: 0, skewX: 20 });
    
    // Animate In at second 1.0
    ltTimeline.to('.lower-third-element', {
        x: 0,
        opacity: 1,
        skewX: 0,
        duration: 0.6,
        stagger: 0.1,
        ease: "power4.out"
    }, 1.0);
    
    // Animate Out at second 4.0
    ltTimeline.to('.lower-third-element', {
        x: -800,
        opacity: 0,
        skewX: -20,
        duration: 0.4,
        stagger: -0.05,
        ease: "power3.in"
    }, 4.0);
</script>`;

fs.writeFileSync('my-video/lower-third.html', htmlOutput);
console.log('Successfully compiled Octopus JSON to Hyperframes component.');
